# Every test file has one or more tests...
test_name: Get information about a public gist

# ...and each test has one or more stages
stages:
  - name: Get html url of public gist
    # Define a request to be made...
    request:
      url: "https://api.github.com/gists/0272ed55620c0e55c6ee132fb348b284"
      method: GET
    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        html_url: "https://gist.github.com/0272ed55620c0e55c6ee132fb348b284"

  - name: Get owner name of public gist
    request:
      url: "https://api.github.com/gists/0272ed55620c0e55c6ee132fb348b284"
      method: GET
    response:
      status_code: 200
      body:
        # Take note of the dot notation 
        owner.login: "tavern-workshop"

  - name: Get content of public gist
    request:
      url: "https://api.github.com/gists/0272ed55620c0e55c6ee132fb348b284"
      method: GET
    response:
      status_code: 200
      body:
        files.demo_gist.content: "Welcome to today's workshop on Tavern!"
